# Generated by Django 3.0.5 on 2020-12-12 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True, unique=True)),
                ('funcion', models.CharField(max_length=60, null=True)),
                ('observacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50, verbose_name='la Direccion')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tfno', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reparticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True, unique=True)),
                ('ubicacion', models.CharField(max_length=60, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('encargado', models.CharField(blank=True, max_length=70)),
                ('observacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('dni', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('fecha_llegada', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(default=django.utils.timezone.now)),
                ('estado_reserva', models.BooleanField(default=False)),
                ('cabana', models.CharField(max_length=50)),
                ('cant_personas', models.IntegerField(blank=True, null=True)),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservo', to='appreclamo.Viajero')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_reclamo', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('Pedido_por', models.CharField(blank=True, max_length=60)),
                ('prioridad_reclamo', models.CharField(blank=True, choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], max_length=10)),
                ('estadia_reclamo', models.CharField(blank=True, choices=[('1', 'Realizado'), ('2', 'Pendiente'), ('3', 'Paralizado')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=150)),
                ('Fecha_realizado', models.DateField(blank=True, null=True)),
                ('cod_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appreclamo.Agentes', to_field='nombre')),
                ('cod_repart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appreclamo.Reparticion', to_field='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='appreclamo.Viajero')),
            ],
        ),
    ]
