# Generated by Django 3.0.5 on 2021-01-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreclamo', '0002_empleados_funcion_sitlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_anuncio', models.DateField()),
                ('Titulo', models.CharField(blank=True, max_length=50)),
                ('Mensaje1', models.CharField(max_length=150, null=True)),
                ('Mensaje2', models.CharField(blank=True, max_length=150)),
                ('Mensaje3', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
